### Scikit-Learning from DataCamp

In [1]:
# a basic example and keras intro

In [80]:
from sklearn import neighbors, datasets, preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import pandas as pd

In [56]:
import warnings
warnings.filterwarnings("ignore")

In [9]:
# load data
iris=datasets.load_iris()
type(iris)

sklearn.utils.Bunch

In [10]:
X, y=iris.data[:, :2], iris.target

In [15]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [17]:
X[0:10]

array([[5.1, 3.5],
       [4.9, 3. ],
       [4.7, 3.2],
       [4.6, 3.1],
       [5. , 3.6],
       [5.4, 3.9],
       [4.6, 3.4],
       [5. , 3.4],
       [4.4, 2.9],
       [4.9, 3.1]])

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=33)

In [13]:
scaler=preprocessing.StandardScaler().fit(X_train)

In [14]:
X_train=scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [18]:
knn=neighbors.KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [19]:
y_pred=knn.predict(X_test)

In [20]:
accuracy_score(y_test, y_pred)

0.631578947368421

In [21]:
# import the metrics class
from sklearn import metrics
cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
cnf_matrix

array([[ 8,  0,  0],
       [ 0,  8,  3],
       [ 0, 11,  8]], dtype=int64)

### Loading data

In [84]:
import numpy as np
X = np.random.random((40, 5))
y = np.array(['M', 'M', 'F', 'F', 'M', 'F', 'M', 'M', 'F', 'F', 'M', 'M', 'F', 'F', 'M', 'F', 'M', 'M', 'F', 'F',
             'M', 'M', 'F', 'F', 'M', 'F', 'M', 'M', 'F', 'F', 'M', 'M', 'F', 'F', 'M', 'F', 'M', 'M', 'F', 'F'])
X[X < 0.6] = 0

In [85]:
X

array([[0.        , 0.        , 0.82563802, 0.69978149, 0.77771584],
       [0.        , 0.63289229, 0.87379052, 0.        , 0.        ],
       [0.80213634, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.67542216, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.86783669, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.72850494],
       [0.        , 0.        , 0.70739317, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.86706606],
       [0.88148795, 0.        , 0.6939295 , 0.        , 0.        ],
       [0.75061402, 0.        , 0.84211596, 0.        , 0.61183123],
       [0.        , 0.76730959, 0.79380082, 0.        , 0.        ],
       [0.91431005, 0.96055976, 0.        , 0.        , 0.68712417],
       [0.        , 0.        , 0.        , 0.        , 0.99828665],
       [0.        , 0.        , 0.85524579, 0.        , 0.        ],
       [0.        , 0.        , 0.

In [86]:
y

array(['M', 'M', 'F', 'F', 'M', 'F', 'M', 'M', 'F', 'F', 'M', 'M', 'F',
       'F', 'M', 'F', 'M', 'M', 'F', 'F', 'M', 'M', 'F', 'F', 'M', 'F',
       'M', 'M', 'F', 'F', 'M', 'M', 'F', 'F', 'M', 'F', 'M', 'M', 'F',
       'F'], dtype='<U1')

### Training and Test Data

In [87]:
from sklearn.model_selection import train_test_split

In [88]:
X_train, X_test, y_train, y_test = train_test_split ( X, y, random_state=0)

### Build models

In [89]:
# Supervised learning estimators

In [90]:
from sklearn.svm import SVC
svc=SVC(kernel='linear')

In [91]:
svc.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [92]:
y_pred = svc.predict (X_test)

### Evaluate model performance

In [93]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.8

In [94]:
# import the metrics class
from sklearn import metrics
cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
cnf_matrix

array([[5, 1],
       [1, 3]], dtype=int64)

In [95]:
X_train.shape

(30, 5)

In [124]:
X_train.shape[1]

5

In [96]:
X_test.shape

(10, 5)

### Use Keras based deep learning for the same X, y data sets

In [97]:
# load libraries
from keras.models import Sequential
from keras.layers import Dense

In [125]:
# configure model
model_k=Sequential()
model_k.add(Dense(32,
         activation='relu',
         input_dim=X_train.shape[1]))  # input_dim=5

model_k.add(Dense(1, activation='sigmoid'))
model_k.compile(optimizer='rmsprop',
               loss='binary_crossentropy',
               metrics=['accuracy'])

In [99]:
# preprocess y for deeplearning format

In [100]:
y = pd.get_dummies(y)

In [102]:
y[0:5]

F  M
0  0  1
1  0  1
2  1  0
3  1  0
4  0  1

In [109]:
y=y.drop('M', axis=1)

In [110]:
# split data set based on 'new' y or label
X_train, X_test, y_train, y_test = train_test_split ( X, y, random_state=0)

In [111]:
X_train[0:5]

array([[0.        , 0.        , 0.        , 0.63333379, 0.        ],
       [0.87192076, 0.        , 0.66880783, 0.        , 0.        ],
       [0.89275757, 0.82490022, 0.63148321, 0.        , 0.        ],
       [0.80213634, 0.        , 0.        , 0.        , 0.        ],
       [0.88304675, 0.        , 0.        , 0.        , 0.        ]])

In [112]:
X_train.shape

(30, 5)

In [113]:
y_test

F
22  1
20  0
25  1
4   0
10  0
15  1
28  1
11  0
18  1
29  1

In [114]:
# fit the model
model_k.fit(X_train, y_train, epochs=10, batch_size=2)

Epoch 1/10
30/30 [==============================] - 0s 6ms/step - loss: 0.6927 - acc: 0.6333
Epoch 2/10
30/30 [==============================] - 0s 760us/step - loss: 0.6885 - acc: 0.6333
Epoch 3/10
30/30 [==============================] - 0s 1ms/step - loss: 0.6854 - acc: 0.6667
Epoch 4/10
30/30 [==============================] - 0s 1ms/step - loss: 0.6831 - acc: 0.6667
Epoch 5/10
30/30 [==============================] - 0s 1ms/step - loss: 0.6807 - acc: 0.6667
Epoch 6/10
30/30 [==============================] - 0s 975us/step - loss: 0.6779 - acc: 0.7000
Epoch 7/10
30/30 [==============================] - 0s 1ms/step - loss: 0.6759 - acc: 0.7000
Epoch 8/10
30/30 [==============================] - 0s 1ms/step - loss: 0.6734 - acc: 0.7000
Epoch 9/10
30/30 [==============================] - 0s 1ms/step - loss: 0.6714 - acc: 0.7000
Epoch 10/10
30/30 [==============================] - 0s 1ms/step - loss: 0.6687 - acc: 0.7000


In [115]:
# predictions
y_pred = model_k.predict(X_test)

In [123]:
# accuracy_score(y_test, y_pred)

In [117]:
# need to convert the prob to '1' or '0' format for performance evaluation
y_pred

array([[0.5248879 ],
       [0.48526186],
       [0.54811734],
       [0.42234704],
       [0.46761042],
       [0.553751  ],
       [0.5791315 ],
       [0.57872856],
       [0.5248238 ],
       [0.480353  ]], dtype=float32)

In [118]:
y_pred[y_pred >0.5]=1

In [119]:
y_pred[y_pred<=0.5]=0

In [120]:
accuracy_score(y_test, y_pred)

0.8

In [121]:
y_test

F
22  1
20  0
25  1
4   0
10  0
15  1
28  1
11  0
18  1
29  1

In [122]:
y_pred

array([[1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.]], dtype=float32)